### ISSUE TITLE
Facebook SDK deprecated

### ISSUE THREAD

**Issue by paul-castro** [luke-hawk/nativescript-fb-analytics#3]
Facebook notifies me that the version of Facebook SDK I was using was deprecated and they will no longer support it.

**Comment by luke-hawk** [comment]
Should be fixed in `1.0.3`

**Comment by paul-castro** [comment]
Thanks bro! Anyway, is this will also take effect on iOS?

**Comment by luke-hawk** [comment]
On iOS it pulls the latest version of the SDK. Let me know when you still face any issues ;)
